name: Sync README's

on:
  schedule:
    - cron: "0 6,12,18,0 * * *"

jobs:
  hetzner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Sync
        run: yarn sync-hetzner
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Sync